description: "IT experience in the development,management,mentoring.Responsibilities in all phases of software development life cycle.<br><a href=\"https://www.linkedin.com/in/urjaramanandi/\">View My LinkedIn Profile</a>"
logo: "/images/logo.png?raw=true"
theme: jekyll-theme-minimal
title: "Urja Ramanandi"
