description: "IT experience in the development,management,mentoring.Responsibilities in all phases of software development life cycle including Analysis, Design, Development, Testing, Implementation, Support and Training.<br><br>Specialties-Web architecture and development.<br>Domain-E-Commerce , CRM,Procurement, Healthcare, Finance (Credit bureau)<br><br><a href=\"https://www.linkedin.com/in/urjaramanandi/\">View My LinkedIn Profile</a>"
logo: "/images/logo.png?raw=true"
theme: jekyll-theme-hacker
title: "Urja Ramanandi"
